module.exports = {
  semi: true,
  singleQuote: true,
  trailingComma: 'all',
  bracketSpacing: true,
  jsxSingleQuote: false,
  jsxBracketSameLine: false,
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  arrowParens: 'always',
  singleAttributePerLine: true,
  proseWrap: 'always',
  htmlWhitespaceSensitivity: 'ignore',
  endOfLine: 'lf',
  quoteProps: 'as-needed',
};
